version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - ather
    volumes:
      - ./logs:/home/app-user/logs # Volume mount to get log files
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - db_data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - ather

volumes:
   db_data: # Named volume..
      
networks:
  ather:
